version: 1
disable_existing_loggers: false

formatters:
  colored:
    class: colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  detailed:
    class: logging.Formatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: output/scheduler.log

loggers:
  app:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  models.observer:
    level: INFO
    handlers: [console, file]
    propagate: no
  app.routers.admin_routes:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]